pipeline {

    agent any

    environment {
        DOCKER_ID = "kamilburuk"
        DOCKER_IMAGE_1 = "liora-jenkins-exam-cast-service"
        DOCKER_IMAGE_2 = "liora-jenkins-exam-movie-service"
        DOCKER_TAG = "v.${BUILD_ID}.0"
    }

    stages {

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                        -t $DOCKER_ID/$DOCKER_IMAGE_1:$DOCKER_TAG \
                        -t $DOCKER_ID/$DOCKER_IMAGE_1:latest \
                        ./cast-service

                    docker build \
                        -t $DOCKER_ID/$DOCKER_IMAGE_2:$DOCKER_TAG \
                        -t $DOCKER_ID/$DOCKER_IMAGE_2:latest \
                        ./movie-service
                '''
            }
        }

        stage('Docker Push') {

            environment {
                DOCKER_PASS = credentials('DOCKER_HUB_PASS')
            }

            steps {
                sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_ID --password-stdin

                    docker push $DOCKER_ID/$DOCKER_IMAGE_1:$DOCKER_TAG
                    docker push $DOCKER_ID/$DOCKER_IMAGE_1:latest

                    docker push $DOCKER_ID/$DOCKER_IMAGE_2:$DOCKER_TAG
                    docker push $DOCKER_ID/$DOCKER_IMAGE_2:latest
                '''
            }
        }

        stage('Deploy DEV') {
            steps {
                sh '''
                    helm upgrade --install movie-app ./charts -n dev
                '''
            }
        }

        stage('Acceptance Test DEV') {
            steps {
                sh '''
                    kubectl rollout status deployment/cast-service -n dev --timeout=120s
                    kubectl rollout status deployment/movie-service -n dev --timeout=120s
                    kubectl rollout status deployment/nginx -n dev --timeout=120s
                '''
            }
        }

        stage('Deploy QA') {
            steps {
                sh '''
                    helm upgrade --install movie-app ./charts -n qa
                '''
            }
        }

        stage('Deploy STAGING') {
            steps {
                sh '''
                    helm upgrade --install movie-app ./charts -n staging
                '''
            }
        }

        stage('Deploy PROD') {
            steps {
                input message: 'Deploy to PROD?'
                sh '''
                    helm upgrade --install movie-app ./charts -n prod
                '''
            }
        }
    }
}
