pipeline {

    environment {
        DOCKER_ID = "kamilburuk"
        DOCKER_IMAGE_1 = "liora-jenkins-exam-cast-service"
	DOCKER_IMAGE_2 = "liora-jenkins-exam-movie-service"
        DOCKER_TAG = "v.${BUILD_ID}.0"
    }

    agent any

    stages {

        stage('Docker Build') {

            steps {
                script {
                    sh '''
                        docker rm -f cast-service || true
			docker rm -f movie-service || true

                        docker build -t $DOCKER_ID/$DOCKER_IMAGE_1:$DOCKER_TAG ./cast-service
			
			docker build -t $DOCKER_ID/$DOCKER_IMAGE_2:$DOCKER_TAG ./movie-service
                    '''
                }
            }
        }

        stage('Docker Run') {

            steps {
                script {
                    sh '''
                        docker run -d -p 8002:8000 \
                        --name cast-service \
                        $DOCKER_ID/$DOCKER_IMAGE_1:$DOCKER_TAG

			sleep 5

			docker run -d -p 8001:8000 \
                        --name movie-service \
                        $DOCKER_ID/$DOCKER_IMAGE_2:$DOCKER_TAG

                        sleep 5
                    '''
                }
            }
        }

        stage('Test Acceptance') {

            steps {
                script {
                    sh '''
			curl --fail -I localhost:8001/api/v1/movies/docs
			curl --fail -I localhost:8002/api/v1/casts/docs
                    '''
                }
            }
        }

        stage('Docker Push') {

            environment {
                DOCKER_PASS = credentials("DOCKER_HUB_PASS")
            }

            steps {
                script {
                    sh '''
                        docker login -u $DOCKER_ID -p $DOCKER_PASS

                        docker push $DOCKER_ID/$DOCKER_IMAGE_1:$DOCKER_TAG

			docker push $DOCKER_ID/$DOCKER_IMAGE_2:$DOCKER_TAG
                    '''
                }
            }
        }
