---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.images.cast.database.name }}
  name: {{ .Values.images.cast.database.name }}
spec:
  replicas: {{ .Values.images.cast.database.replicas }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.images.cast.database.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.images.cast.database.name }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cast_db_dev
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_USER
              value: cast_db_username
          image: "{{ .Values.images.cast.database.repository }}:{{ .Values.images.cast.database.tag }}"
          name: {{ .Values.images.cast.database.name }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-cast
      restartPolicy: Always
      volumes:
        - name: postgres-data-cast
          persistentVolumeClaim:
            claimName: postgres-data-cast

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.images.movie.database.name }}
  name: {{ .Values.images.movie.database.name }}
spec:
  replicas: {{ .Values.images.movie.database.replicas }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.images.movie.database.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: movie-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: movie_db_dev
            - name: POSTGRES_PASSWORD
              value: movie_db_password
            - name: POSTGRES_USER
              value: movie_db_username
          image: "{{ .Values.images.movie.database.repository }}:{{ .Values.images.movie.database.tag }}"
          name: {{ .Values.images.movie.database.name }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-movie
      restartPolicy: Always
      volumes:
        - name: postgres-data-movie
          persistentVolumeClaim:
            claimName: postgres-data-movie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.images.cast.name }}
  name: {{ .Values.images.cast.name }}
spec:
  replicas: {{ .Values.images.cast.replicas }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.images.cast.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.images.cast.name }}
    spec:
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "{{ .Values.images.cast.containerPort }}"
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev
          image: "{{ .Values.images.cast.repository }}:{{ .Values.images.cast.tag }}"
          name: {{ .Values.images.cast.name }}
          ports:
            - containerPort: {{ .Values.images.cast.containerPort }}
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.images.movie.name }}
  name: {{ .Values.images.movie.name }}
spec:
  replicas: {{ .Values.images.movie.replicas }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.images.movie.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.images.movie.name }}
    spec:
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "{{ .Values.images.movie.containerPort }}"
          env:
            - name: CAST_SERVICE_HOST_URL
              value: http://cast-service:8000/api/v1/casts/
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
          image: "{{ .Values.images.movie.repository }}:{{ .Values.images.movie.tag }}"
          name: {{ .Values.images.movie.name }}
          ports:
            - containerPort: {{ .Values.images.movie.containerPort }}
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.images.nginx.name }}
  name: {{ .Values.images.nginx.name }}
spec:
  replicas: {{ .Values.images.nginx.replicas }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.images.nginx.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.images.nginx.name }}
    spec:
      containers:
        - image: "{{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}"
          name: nginx
          ports:
            - containerPort: {{ .Values.images.nginx.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-cm0
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx_config.conf
                path: default.conf
            name: nginx-cm0
          name: nginx-cm0
