images:
  cast:
    repository: kamilburuk/liora-jenkins-exam-cast-service
    tag: latest
    containerPort: 8000
    name: cast-service
    replicas: 1

    database:
      repository: postgres
      tag: 12.1-alpine
      name: cast-db
      replicas: 1

  movie:
    repository: kamilburuk/liora-jenkins-exam-movie-service
    tag: latest
    containerPort: 8000
    name: movie-service
    replicas: 1

    database:
      repository: postgres
      tag: 12.1-alpine
      name: movie-db
      replicas: 1

  nginx:
    repository: nginx
    tag: latest
    containerPort: 8080
    name: nginx
    replicas: 1
